const truck_category_packagesSchema = mongoose.Schema({
	_id: {type: Number, required: true},
	package_category_id: {type: Number, required: true},
	display_text: {type: String, required: true},
	seo_name: {type: String, required: false},
	short_description: {type: String, required: true},
	long_description: {type: String, required: true},
	image_1_url: {type: String, required: false},
	image_1_alt_text: {type: String, required: false},
	image_2_url: {type: String, required: false},
	image_2_alt_text: {type: String, required: false},
	image_3_url: {type: String, required: false},
	image_3_alt_text: {type: String, required: false},
	image_4_url: {type: String, required: false},
	image_4_alt_text: {type: String, required: false},
	image_5_url: {type: String, required: false},
	image_5_alt_text: {type: String, required: false},
	image_6_url: {type: String, required: false},
	image_6_alt_text: {type: String, required: false},
	image_7_url: {type: String, required: false},
	image_7_alt_text: {type: String, required: false},
	image_8_url: {type: String, required: false},
	image_8_alt_text: {type: String, required: false},
	seq_no: {type: Number, required: false},
}, {collection: 'truck_category_packages'});